#!/bin/sh
### BEGIN INIT INFO
# Provides:          dxrtd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DEEPX Runtime Daemon
### END INIT INFO

case "$1" in
  start)
    echo "Starting dxrtd..."
    start-stop-daemon -S -b -x /usr/bin/dxrtd
    ;;
  stop)
    echo "Stopping dxrtd..."
    start-stop-daemon -K -x /usr/bin/dxrtd
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0